# Generated by Django 2.1.5 on 2019-05-08 07:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190507_2121'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='habsuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
