# Generated by Django 2.1.5 on 2019-05-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190507_1111'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='habsuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='habsuser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Enter first name', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='habsuser',
            name='institution',
            field=models.CharField(help_text='UP-MSI, BFAR, DENR, etc.', max_length=100, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='habsuser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Enter last name', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='habsuser',
            name='position',
            field=models.CharField(help_text='i.e. Professor, SRS, etc.', max_length=50, verbose_name='Position'),
        ),
    ]
