# Generated by Django 2.1.5 on 2019-05-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habdb', '0002_auto_20190528_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planktonsample',
            old_name='species',
            new_name='plankton',
        ),
        migrations.RenameField(
            model_name='planktonsample',
            old_name='sample_id',
            new_name='sample',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='date',
            new_name='sample_date',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='depth',
            new_name='sample_depth',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='station_name',
            new_name='station',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
