# Generated by Django 2.2.2 on 2019-06-19 08:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habdb', '0007_remove_station_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('station_name',), 'verbose_name_plural': 'stations'},
        ),
        migrations.AddField(
            model_name='station',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
