# Generated by Django 2.2.2 on 2019-06-19 08:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habdb', '0008_auto_20190619_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(12.5 121.98)', srid=4326),
        ),
    ]
