# Generated by Django 2.2.2 on 2019-06-20 05:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habdb', '0009_auto_20190619_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(121.98 12.5)', srid=4326),
        ),
    ]
