# Generated by Django 2.2.2 on 2019-06-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habdb', '0010_auto_20190620_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=13),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=13),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_depth',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
