# Generated by Django 2.2.2 on 2019-06-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habdb', '0004_auto_20190606_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='NH3',
            new_name='conductivity',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='NH4',
            new_name='nh3',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='NO2',
            new_name='nh4',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='NO3',
            new_name='no2',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='PO4',
            new_name='no3',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sample_id',
        ),
        migrations.AddField(
            model_name='sample',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='po4',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, null=True),
        ),
    ]
