# Generated by Django 2.2.2 on 2019-07-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habdb', '0005_auto_20190620_1205'),
        ('habdb', '0011_auto_20190621_1442'),
    ]

    operations = [
    ]
